### ISSUE TITLE
Missing informations

### ISSUE THREAD

**Issue by AndiBcool** [neogeodev/NeoMemCard2#1]
For people that want to crosscheck this stuff, here is some more information:

The PCB thinkness should be 1 mm ( thats seems to be a long email assistance )
The Vcc in shematics is actually 5V. 
You wont find this information here, the creator does not even mention it. 

Its important to know when the creator links a flashchip component with 3,6V max ( FM28V020 ) and even admit he had issues with this type of chip in the past himself. 
http://collguy.bplaced.net/fail.jpg

The PCB layout is missing components marks, here is a pic with added marks: http://collguy.bplaced.net/neomemcard2_no_ss.png

Now imagine if someone tells the creator all this stuff, that he should add this information for others and he acts like a child.

**Comment by furrtek** [comment]
Hello Andi. A question for you: how does entitlement, expecting guarantees from free stuff, not knowing how to read and irresponsibility rank on the childish behavior scale ?

You're a true model. I'm getting along way too well with people nowadays and would like some advice on how to fix that. Can you help me lose my friends and be hated by everyone on the internet ?

**Comment by AndiBcool** [comment]
Mate i only asked you about the thickness of the PCB and did suggest to add part placement.

The 2nd email i did send you was already related to the wrong flash chip you had in the list, because the card did not work.

I could not beleave that someone that is so proffessional with electronics and already builded this cards put up a half baked, wrong and missing instructions.

Even you did admid you had problems with this wrong listed chip yourself: " I got many fake FRAM chips from Aliexpress, either as re-branded SRAM or completely dead chips.
I've had luck with this seller: https://www.ebay.fr/itm/FM18W08-SG-SOP-28-F-RAM-256Kb-70ns-32K-x-8-Parallel-FRAM/292645154175?hash=item442302ad7f:g:doAAAOSw9ytZnU6u"

No the chips where good but could not survive 5V ( one got tested in a N64 controller save RAM).
You seem to have no clue whats wrong but reffered me a different flash chip (that actually works with up to 5,5V).

I cant read whats not written or is just plain wrong.
In my 3rd mail i did inform you about your mistakes.

I did not ask for money or any replacement or gurantee for my lost/ destroyed chips because of your mistake. 
I only did inform, i found the error why the  the whole design, you put up, did not work and that you should change that quick for other people.

You did not care and so i did put up the missing information.

Im surly to blame for beleaving in an an expert and expecting he puts up correct informations (free or not).

As for your question, you do rather well, lately.
